### ISSUE TITLE
Domain name is expired?

### ISSUE THREAD

**Issue by benwr** [EloiseRosen/admonymous#5]
Just tried to go to admonymous.com, and discovered that the domain name seems to have expired, and now shows some registrar's page.

**Comment by benwr** [comment]
(I'm not sure this is the right place to report the issue; please point me in the right direction if not)

**Comment by EloiseRosen** [comment]
Thanks! This is now resolved - the new domain name is admonymous.co. (Unfortunately someone else bought the old one after it expired.) An email will be going out shortly to inform all users.
